### ISSUE TITLE
YAML merge syntax doesn't appear to be handled

### ISSUE THREAD

**Issue by zero1zero** [FasterXML/jackson-dataformat-yaml#20]
In transitioning a SnakeYAML implementation over to one going through Jackson, it would appear that YAML merge functionality does not work.  

Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized field "<<" (class com.thing.config.Config), not marked as ignorable (3 known properties: "port", "scheme", "version"])

YAML used:

``` yaml
default: &default
    version: 1

dev: &dev
    <<: *default
    scheme: http
    port: 8080
```

Calling code:

``` java
ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
JsonNode node = mapper.readTree(yaml);
```

Node variable contains '<<' named properties instead of expected behavior of a merged JsonNode
