### ISSUE TITLE
Polymorphic mapping may work correctly

### ISSUE THREAD

**Issue by xzer** [FasterXML/jackson-dataformat-yaml#73]
I am not familiar with YML format, I also found the existing ticket #21, but it seems that the current implementation does not work as common sense.

At first, there is an example showing how to perform polymorphic mapping with json:

https://gist.github.com/xzer/fd854576dee3bf7a3f7e4695ec987ce0

Simply, if we using following annotation on the parent class,

```java
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME,
              include=JsonTypeInfo.As.PROPERTY,
              property="type")
@JsonSubTypes({
        @JsonSubTypes.Type(value=Dog.class, name="dog"),
        @JsonSubTypes.Type(value=Cat.class, name="cat"),
    })
```

we should get the following output for serialization:

```javascript
{
 "animals" : [ {
    "type" : "dog",
    "name" : "Dog1"
  }, {
    "type" : "cat",
    "name" : "Cat1"
  }
 } ]
}
```

The type property will suggest the correct type of current object. 

But, for yaml serialization, I expect the following output:

```yaml
animals: 
  - type: "dog"
    name: "Dog1"
  - type: "cat"
    name: "Cat1"
```

but I got the following:

```yaml
animals: 
  - !<dog>
    name: "Dog1"
  - !<cat>
    name: "Cat1"
```

My question is that whether the above output is by design? And how can I get the type informatio with property as the same as the json format?

Or is it a bug?
