### ISSUE TITLE
Avoid exposing implementation details

### ISSUE THREAD

**Issue by DaveJarvis** [FasterXML/jackson-dataformat-yaml#74]
# Background

Making a recursive delimited reference resolver for YAML. For example:

```
$ cat variables.yaml 

---
a: A
b: $a$ B
c: $b$ C $b$
d: $a$ $b$ $c$ D $a$
```

Then:

```
$ java -jar target/yamlp.jar --input variables.yaml 

---
a: "A"
b: "A B"
c: "A B C A B"
d: "A A B A B C A B D A"
```
# Problem

The application [source code](https://bitbucket.org/djarvis/yamlp/src/master/src/main/java/com/whitemagicsoftware/yamlp/Main.java) is fairly clean, except for the following inner classes:

```
  private class ResolverYAMLFactory extends YAMLFactory {

    @Override
    protected YAMLGenerator _createGenerator(
      Writer out, IOContext ctxt ) throws IOException {
      return new ResolverYAMLGenerator(
        ctxt, _generatorFeatures, _yamlGeneratorFeatures, _objectCodec,
        out, _version );
    }
  }

  private class ResolverYAMLGenerator extends YAMLGenerator {

    public ResolverYAMLGenerator(
      IOContext ctxt,
      int jsonFeatures,
      int yamlFeatures,
      ObjectCodec codec,
      Writer out,
      DumperOptions.Version version ) throws IOException {
      super( ctxt, jsonFeatures, yamlFeatures, codec, out, version );
    }

    @Override
    public void writeString( String text )
      throws IOException, JsonGenerationException {
      super.writeString( substitute( text ) );
    }
  }
```
# Resolution

Is there an easy way to inject a YAML serializer as a module? If not, there is a lot of internal "knowledge" about how YAML generation works exposed to my application, as per the two aforementioned inner classes. If a YAML serializer was available, or a documented example made available, that would be ideal. Otherwise, consider the following as an idealized version (i.e., that limits coupling between a client and the YAML factory/generator implementation):

```
  private class ResolverYAMLFactory extends YAMLFactory {

    @Override
    protected YAMLGenerator createGenerator() throws IOException {
      return new ResolverYAMLGenerator();
    }
  }
```

The superclass (`YAMLFactory`) would then do something like:

```
private YAMLGenerator _createGenerator( Writer out, IOContext c ) throws IOException {
    // Simple API for subclasses
    YAMLGenerator g = createGenerator();

    // Initialize the required state.
    g.setWriter( out );
    g.setContext( context );
    return g;;
}
```

Similarly, the same approach could be taken for the YAMLGenerator:

```
  private class ResolverYAMLGenerator extends YAMLGenerator {

    public ResolverYAMLGenerator() {
    }

    @Override
    public void writeString( String text )
      throws IOException, JsonGenerationException {
      super.writeString( substitute( text ) );
    }
  }
```

This would require refactoring the YAMLGenerator with numerous set accessor methods that allow state and behaviour changes, rather than exposing required bits as protected variables. This would also eliminate unwieldy method and constructor signatures.

That is to say, client code looking to inject some simple customizations in the YAML output shouldn't need to know about `_generatorFeatures`, `_yamlGeneratorFeatures`, and the other implementation details being exposed.

**Comment by cowtowncoder** [comment]
@DaveJarvis As a general rule, we are always open to improvements in code hygieny, clean design.

But in this case I think it would be useful to back down a little bit and explain what you are trying to do, and the need for customizations. Ideally any details of underlying YAML emitter/parser (SnakeYAML) would be fully encapsulated and hidden; but for practical reasons we sometimes may need to expose them, and then the question is that of what's the best balance between work to write things, add `YAMLParser.Feature` / `YAMLGenerator.Feature` vs. just exposing internal `SnakeYAML` endpoints.

As a general rule, without knowing about details, we would prefer users never (having to) sub-class either factory or parser / generator classes.

**Comment by DaveJarvis** [comment]
@cowtowncoder:

> explain what you are trying to do

A YAML file contains references to other YAML variables. The names of the variables can be anything. For example:

```
c:
  minor:
    secondary:
       name:
        First: Tatu
        First_pos: $c.minor.secondary.name.First$'s
        Middle: CowTownCoder
        Family: Saloranta
        Full: $c.minor.secondary.name.First$ $c.minor.secondary.name.Middle$ $c.minor.secondary.name.Family$

p:
  log: $c.minor.secondary.name.First_pos$ Adventures in Coding

timeline:
  birthdate:
    year: 1995
  job:
    interview:
      year: $timeline.birthdate.year$ + 20
```

The structure of the document can change any time. The names aren't fixed. I'm looking for a general-purpose solution to recursively replace the values, without knowing anything about the YAML data structure:

```
c:
  minor:
    secondary:
       name:
        First: Tatu
        First_pos: Tatu's
        Middle: CowTownCoder
        Family: Saloranta
        Full: Tatu CowTownCoder Saloranta

p:
  log: Tatu's Adventures in Coding

timeline:
  birthdate:
    year: 1995
  job:
    interview:
      year: 1995 + 20
```
